Configure postgresql for stoqserver
Change-Id: I3cc4897ca80520f4c85e5beaba4e3b9cfafe7c9e

diff --git a/debian/stoq-server.postinst b/debian/stoq-server.postinst
--- a/debian/stoq-server.postinst
+++ b/debian/stoq-server.postinst
@@ -19,6 +19,18 @@ case "$1" in
         # Make sure stoqserver's home exists
         mkdir -p /usr/share/stoqserver || true
 
+        if [ -d "/var/run/postgresql" ]; then
+            PORT="`find /var/run/postgresql -regex '.*\.s\.PGSQL\.[0-9]+' | sort | tail -n1`"
+            PORT="`echo $PORT | sed -e 's/\(.*\.\)\([0-9]\+\)/\2/'`"
+            # If the process above failed for some reason, use the default 5432
+            if [ -z "$PORT" ]; then
+                PORT="5432"
+            fi
+        else
+            PORT="5432"
+        fi
+
+        # Create .stoq dir and configuration if they don't exist
         if [ ! -f /usr/share/stoqserver/.stoq ]; then
             mkdir -p /usr/share/stoqserver/.stoq
             BACKUP_KEY="`cat /dev/urandom | tr -dc _A-Z-a-z-0-9 | head -c64`"
@@ -29,13 +41,29 @@ logfile = /usr/share/stoqserver/.stoq/stoqserver.log
 [Database]
 rdbms = postgres
 address = 
-port = 5432
+port = $PORT
 dbname = stoq
-dbusername = stoq
+dbusername = stoqserver
 
 [Backup]
 key = $BACKUP_KEY
 EOF
+        fi
+
+        # Create the stoqserver dbuser on postgresql if it doesn't exist
+        HAS_USER_QUERY="SELECT usename FROM pg_user WHERE usename = 'stoqserver';"
+        set +e
+        HAS_USER="`sudo -u postgres psql -p $PORT -c "$HAS_USER_QUERY" | grep -c $USERNAME`"
+        set -e
+        if [ "$HAS_USER" != "1" ]; then
+            sudo -u postgres createuser -p $PORT -dsR stoqserver || true
+        fi
+
+        # Create a .pgpass file stoqserver
+        if [ ! -f /usr/share/stoqserver/.pgpass ]; then
+            PG_PASSWORD="`cat /dev/urandom | tr -dc _A-Z-a-z-0-9 | head -c32`"
+            echo "*:*:*:stoqserver:$PG_PASSWORD" > /usr/share/stoqserver/.pgpass
+            chmod 0600 /usr/share/stoqserver/.pgpass
         fi
 
         # Create stoqserver user if it doesn't exist
